# Default values.yaml for counter-service app

global:
  appName: counter-better
  namespace: dev

deployment:
  rollingUpdate:
    maxUnavailable: 0
  
  container:
    appImage: eilon01/counter-better
    appTag: f79e764
    imagePullPolicy: Always  

    port:
      portName: http
      containerPort: 80
    
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m

service:
  serviceType: LoadBalancer
  annotations: {}
  protocol: TCP 
  port: 81
  targetPort: 80

  ingress:
    create: true

configmap:
  data:
    REDIS_HOST: counter-better-redis-master
    REDIS_PORT: "6379" 

horizontalPodAutoscaler:
  minReplicas: 2
  maxReplicas: 5
  resource:
    cpuAverageUtilization: 80
    memoryAverageUtilization: 80
