name: Merge Deployment Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
    types: [ opened, reopened ]

jobs:
  determine-environment-and-tag:
    uses: ./.github/workflows/determine-environment-and-tag.yaml
  
  load-env-vars:
    runs-on: ubuntu-latest
    needs:
      - lint-helm
      - determine-environment-and-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download environment data
        uses: actions/download-artifact@v3
        with:
          name: environment-data

      - name: Read environment variables from file
        id: read-env
        run: |
          source outputs.txt
          echo "ENV=${env}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${image_tag}" >> $GITHUB_ENV

  deploy-preprod:
    uses: ./.github/workflows/deploy-template.yaml
    needs:
      - determine-environment-and-tag
    with:
      env: ${{ needs.determine-environment-and-tag.outputs.env }}

  tag-and-release:
    uses: ./.github/workflows/create-tag.yml
    with:
      branch_name: ${{ github.ref_name }}
      commit_message: ${{ github.event.head_commit.message }}
  
  deploy-prod:
    uses: ./.github/workflows/deploy-template.yaml
    needs:
      - tag-and-release
      - determine-environment-and-tag
    with:
      env: "prod"