# .github/workflows/determine-environment-and-tag.yaml
name: Determine Environment
on:
  workflow_call:
    
jobs:
  determine-environment-and-tag:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.gen-output.outputs.env }}
      image_tag: ${{ steps.gen-output.outputs.image_tag }}
    steps:
      - name: Determine environment and image tag
        id: gen-output
        run: |
          # Determine environment and image tag based on the ref name
          if [[ "${GITHUB_REF_NAME}" == "main" || "${GITHUB_REF_NAME}" == "master" ]]; then
            env="preprod"
            image_tag="main"
          elif [[ "${GITHUB_REF_NAME}" == v* ]]; then
            env="prod"
            image_tag=$(echo "${GITHUB_REF_NAME}")
          else
            branch_name=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]')
            env="dev"
            image_tag=${branch_name}
          fi

          # Set outputs for the workflow
          echo "env=${env}" >> $GITHUB_ENV
          echo "image_tag=${image_tag}" >> $GITHUB_ENV


          # Print the values to the log for debugging
          echo "ENV=${env}"
          echo "IMAGE_TAG=${image_tag}"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
  debug:
    runs-on: ubuntu-latest
    needs: determine-environment-and-tag
    steps:
      - name: print
        run: |
          echo "ENV=${{needs.determine-environment-and-tag.outputs.output_image_tag}}"
          echo "IMAGE_TAG=${{needs.determine-environment-and-tag.outputs.output_env}}"